# Generated by Django 6.0.3 on 2026-03-10 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='pressure_index',
            field=models.PositiveSmallIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='scenario',
            name='step_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='weather_index',
            field=models.PositiveSmallIntegerField(default=35),
        ),
        migrations.AddField(
            model_name='unit',
            name='morale',
            field=models.PositiveSmallIntegerField(default=75),
        ),
        migrations.CreateModel(
            name='SimulationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('phase', models.CharField(max_length=64)),
                ('tempo', models.PositiveSmallIntegerField()),
                ('intel_confidence', models.PositiveSmallIntegerField()),
                ('weather_index', models.PositiveSmallIntegerField()),
                ('pressure_index', models.PositiveSmallIntegerField()),
                ('readiness_avg', models.PositiveSmallIntegerField()),
                ('supply_avg', models.PositiveSmallIntegerField()),
                ('morale_avg', models.PositiveSmallIntegerField()),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='simulator.scenario')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
