# Generated by Django 5.1.6 on 2026-03-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_objective_progress_scenario_pressure_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='end_reason',
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.AddField(
            model_name='scenario',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='reserve_supplies',
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='scenario',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('won', 'Победа'), ('lost', 'Поражение')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='scenario',
            name='step_limit',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='unit',
            name='pos_x',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='pos_y',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
